# Generated by Django 3.2.9 on 2021-12-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('saler', 'saler'), ('manager', 'manager'), ('technician', 'technician')], default=1, max_length=10),
        ),
    ]
